<?xml version='1.0'?>

<!--
This file catalogues IDL syntax elements contained in
the IDL HTML documentation set.
Catalog created 2009-4-8
-->

<!DOCTYPE CATALOG [
   <!ELEMENT CATALOG (ROUTINE* | CLASS* | SYSVAR* | STATEMENT*)>
   <!ATTLIST CATALOG name CDATA #IMPLIED>
   <!ATTLIST CATALOG version CDATA #IMPLIED>
   <!ELEMENT ROUTINE (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST ROUTINE name CDATA #IMPLIED>
   <!ATTLIST ROUTINE link CDATA #IMPLIED>
   <!ATTLIST ROUTINE alias_to CDATA #IMPLIED>
   <!ELEMENT STATEMENT EMPTY >
   <!ATTLIST STATEMENT name CDATA #IMPLIED>
   <!ATTLIST STATEMENT link CDATA #IMPLIED>
   <!ATTLIST STATEMENT alias_to CDATA #IMPLIED>
   <!ELEMENT SYNTAX EMPTY>
   <!ATTLIST SYNTAX name CDATA #IMPLIED>
   <!ATTLIST SYNTAX type CDATA #IMPLIED>
   <!ELEMENT ARGUMENT EMPTY>
   <!ATTLIST ARGUMENT name CDATA #IMPLIED>
   <!ATTLIST ARGUMENT link CDATA #IMPLIED>
   <!ELEMENT KEYWORD EMPTY>
   <!ATTLIST KEYWORD name CDATA #IMPLIED>
   <!ATTLIST KEYWORD link CDATA #IMPLIED>
   <!ELEMENT CLASS (SUPERCLASS* | PROPERTY* | METHOD*)>
   <!ATTLIST CLASS name CDATA #IMPLIED>
   <!ATTLIST CLASS link CDATA #IMPLIED>
   <!ELEMENT SUPERCLASS EMPTY>
   <!ATTLIST SUPERCLASS name CDATA #IMPLIED>
   <!ATTLIST SUPERCLASS link CDATA #IMPLIED>
   <!ELEMENT PROPERTY EMPTY>
   <!ATTLIST PROPERTY name CDATA #IMPLIED>
   <!ATTLIST PROPERTY link CDATA #IMPLIED>
   <!ATTLIST PROPERTY get CDATA #IMPLIED>
   <!ATTLIST PROPERTY set CDATA #IMPLIED>
   <!ATTLIST PROPERTY init CDATA #IMPLIED>
   <!ATTLIST PROPERTY registered CDATA #IMPLIED>
   <!ELEMENT METHOD (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST METHOD name CDATA #IMPLIED>
   <!ATTLIST METHOD link CDATA #IMPLIED>
   <!ELEMENT SYSVAR (FIELD*)>
   <!ATTLIST SYSVAR name CDATA #IMPLIED>
   <!ATTLIST SYSVAR link CDATA #IMPLIED>
   <!ATTLIST SYSVAR alias_to CDATA #IMPLIED>
   <!ELEMENT FIELD EMPTY>
   <!ATTLIST FIELD name CDATA #IMPLIED>
   <!ATTLIST FIELD link CDATA #IMPLIED>
]>

<CATALOG name="IDL" version="7.1">
<ROUTINE name=".COMPILE" link=".COMPILE.html">
  <SYNTAX name=".COMPILE [File1, ..., Filen]" type="exec" />
  <SYNTAX name=".COMPILE -f File TempFile" type="exec" />
</ROUTINE>
<ROUTINE name=".CONTINUE" link=".CONTINUE.html">
  <SYNTAX name=".CONTINUE" type="exec" />
</ROUTINE>
<ROUTINE name=".EDIT" link=".EDIT.html">
  <SYNTAX name=".EDIT File1 [File2 ... Filen]" type="exec" />
</ROUTINE>
<ROUTINE name=".FULL_RESET_SESSION" link=".FULL_RESET_SESSION.html">
  <SYNTAX name=".FULL_RESET_SESSION" type="exec" />
</ROUTINE>
<ROUTINE name=".GO" link=".GO.html">
  <SYNTAX name=".GO" type="exec" />
</ROUTINE>
<ROUTINE name=".OUT" link=".OUT.html">
  <SYNTAX name=".OUT" type="exec" />
</ROUTINE>
<ROUTINE name=".RESET_SESSION" link=".RESET_SESSION.html">
  <SYNTAX name=".RESET_SESSION" type="exec" />
</ROUTINE>
<ROUTINE name=".RETURN" link=".RETURN.html">
  <SYNTAX name=".RETURN" type="exec" />
</ROUTINE>
<ROUTINE name=".RNEW" link=".RNEW.html">
  <SYNTAX name=".RNEW [File1, ..., Filen]" type="exec" />
  <SYNTAX name=".RNEW -L ListFile.lis File1 [, File2, ..., Filen]" type="exec" />
  <SYNTAX name=".RNEW -T File1 [, File2, ..., Filen]" type="exec" />
</ROUTINE>
<ROUTINE name=".RUN" link=".RUN.html">
  <SYNTAX name=".RUN [File1, ..., Filen]" type="exec" />
  <SYNTAX name=".RUN -L ListFile.lis File1 [, File2, ..., Filen]" type="exec" />
  <SYNTAX name=".RUN -T File1 [, File2, ..., Filen]" type="exec" />
</ROUTINE>
<ROUTINE name=".SKIP" link=".SKIP.html">
  <SYNTAX name=".SKIP [n]" type="exec" />
</ROUTINE>
<ROUTINE name=".STEP" link=".STEP.html">
  <SYNTAX name=".STEP [n] or .S [n]" type="exec" />
</ROUTINE>
<ROUTINE name=".STEPOVER" link=".STEPOVER.html">
  <SYNTAX name=".STEPOVER [n] or .SO [n]" type="exec" />
</ROUTINE>
<ROUTINE name=".TRACE" link=".TRACE.html">
  <SYNTAX name=".TRACE" type="exec" />
</ROUTINE>
<ROUTINE name="A_CORRELATE" link="A_CORRELATE.html">
  <SYNTAX name="Result = A_CORRELATE(X, Lag )" type="func" />
  <ARGUMENT name="X" link="A_CORRELATE.html#wp54398" />
  <ARGUMENT name="Lag" link="A_CORRELATE.html#wp54400" />
  <KEYWORD name="COVARIANCE" link="A_CORRELATE.html#wp54405" />
  <KEYWORD name="DOUBLE" link="A_CORRELATE.html#wp826748" />
</ROUTINE>
<ROUTINE name="ABS" link="ABS.html">
  <SYNTAX name="Result = ABS(X)" type="func" />
  <ARGUMENT name="X" link="ABS.html#wp675687" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="ACOS" link="ACOS.html">
  <SYNTAX name="Result = ACOS(X)" type="func" />
  <ARGUMENT name="X" link="ACOS.html#wp809512" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="ADAPT_HIST_EQUAL" link="ADAPT_HIST_EQUAL.html">
  <SYNTAX name="Result = ADAPT_HIST_EQUAL (Image  )" type="func" />
  <ARGUMENT name="Image" link="ADAPT_HIST_EQUAL.html#wp985042" />
  <KEYWORD name="CLIP" link="ADAPT_HIST_EQUAL.html#wp985045" />
  <KEYWORD name="FCN" link="ADAPT_HIST_EQUAL.html#wp987804" />
  <KEYWORD name="NREGIONS" link="ADAPT_HIST_EQUAL.html#wp985047" />
  <KEYWORD name="TOP" link="ADAPT_HIST_EQUAL.html#wp985049" />
</ROUTINE>
<ROUTINE name="ALOG" link="ALOG.html">
  <SYNTAX name="Result = ALOG(X)" type="func" />
  <ARGUMENT name="X" link="ALOG.html#wp675710" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="ALOG10" link="ALOG10.html">
  <SYNTAX name="Result = ALOG10(X)" type="func" />
  <ARGUMENT name="X" link="ALOG10.html#wp675722" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="AMOEBA" link="AMOEBA.html">
  <SYNTAX name="Result = AMOEBA( Ftol )" type="func" />
  <ARGUMENT name="Ftol" link="AMOEBA.html#wp864072" />
  <KEYWORD name="FUNCTION_NAME" link="AMOEBA.html#wp864079" />
  <KEYWORD name="FUNCTION_VALUE" link="AMOEBA.html#wp864085" />
  <KEYWORD name="NCALLS" link="AMOEBA.html#wp864089" />
  <KEYWORD name="NMAX" link="AMOEBA.html#wp864091" />
  <KEYWORD name="P0" link="AMOEBA.html#wp864094" />
  <KEYWORD name="SCALE" link="AMOEBA.html#wp864103" />
  <KEYWORD name="SIMPLEX" link="AMOEBA.html#wp864424" />
</ROUTINE>
<ROUTINE name="ANNOTATE" link="ANNOTATE.html">
  <SYNTAX name="ANNOTATE" type="pro" />
  <KEYWORD name="COLOR_INDICES" link="ANNOTATE.html#wp756628" />
  <KEYWORD name="DRAWABLE" link="ANNOTATE.html#wp756633" />
  <KEYWORD name="LOAD_FILE" link="ANNOTATE.html#wp756636" />
  <KEYWORD name="TEK_COLORS" link="ANNOTATE.html#wp756639" />
  <KEYWORD name="WINDOW" link="ANNOTATE.html#wp756642" />
</ROUTINE>
<ROUTINE name="APP_USER_DIR" link="APP_USER_DIR.html">
  <SYNTAX name="Result = APP_USER_DIR(AuthorDirname, AuthorDesc, AppDirname, AppDesc, AppReadmeText, AppReadmeVersion )" type="func" />
  <ARGUMENT name="AuthorDirname" link="APP_USER_DIR.html#wp1011567" />
  <ARGUMENT name="AuthorDesc" link="APP_USER_DIR.html#wp1011576" />
  <ARGUMENT name="AppDirname" link="APP_USER_DIR.html#wp1011578" />
  <ARGUMENT name="AppDesc" link="APP_USER_DIR.html#wp1011584" />
  <ARGUMENT name="AppReadmeText" link="APP_USER_DIR.html#wp1011586" />
  <ARGUMENT name="AppReadmeVersion" link="APP_USER_DIR.html#wp1011591" />
  <KEYWORD name="AUTHOR_README_TEXT" link="APP_USER_DIR.html#wp1011596" />
  <KEYWORD name="AUTHOR_README_VERSION" link="APP_USER_DIR.html#wp1011600" />
</ROUTINE>
<ROUTINE name="APP_USER_DIR_QUERY" link="APP_USER_DIR_QUERY.html">
  <SYNTAX name="Result = APP_USER_DIR_QUERY(AuthorDirname, AppDirname )" type="func" />
  <ARGUMENT name="AuthorDirname" link="APP_USER_DIR_QUERY.html#wp1011738" />
  <ARGUMENT name="AppDirname" link="APP_USER_DIR_QUERY.html#wp1011743" />
  <KEYWORD name="COUNT" link="APP_USER_DIR_QUERY.html#wp1011749" />
  <KEYWORD name="EXCLUDE_CURRENT" link="APP_USER_DIR_QUERY.html#wp1011751" />
</ROUTINE>
<ROUTINE name="ARG_PRESENT" link="ARG_PRESENT.html">
  <SYNTAX name="Result = ARG_PRESENT(Variable)" type="func" />
  <ARGUMENT name="Variable" link="ARG_PRESENT.html#wp878794" />
</ROUTINE>
<ROUTINE name="ARRAY_EQUAL" link="ARRAY_EQUAL.html">
  <SYNTAX name="Result = ARRAY_EQUAL( Op1 , Op2 )" type="func" />
  <ARGUMENT name="Op1" link="ARRAY_EQUAL.html#wp987066" />
  <ARGUMENT name="Op2" link="ARRAY_EQUAL.html#wp987066" />
  <KEYWORD name="NO_TYPECONV" link="ARRAY_EQUAL.html#wp987069" />
</ROUTINE>
<ROUTINE name="ARRAY_INDICES" link="ARRAY_INDICES.html">
  <SYNTAX name="Result = ARRAY_INDICES(Array, Index  )" type="func" />
  <ARGUMENT name="Array" link="ARRAY_INDICES.html#wp1004211" />
  <ARGUMENT name="Index" link="ARRAY_INDICES.html#wp1004213" />
  <KEYWORD name="DIMENSIONS" link="ARRAY_INDICES.html#wp1004217" />
</ROUTINE>
<ROUTINE name="ARROW" link="ARROW.html">
  <SYNTAX name="ARROW, X0, Y0, X1, Y1" type="pro" />
  <ARGUMENT name="X0" link="ARROW.html#wp756658" />
  <ARGUMENT name="Y0" link="ARROW.html#wp756658" />
  <ARGUMENT name="X1" link="ARROW.html#wp756660" />
  <ARGUMENT name="Y1" link="ARROW.html#wp756660" />
  <KEYWORD name="DATA" link="ARROW.html#wp756664" />
  <KEYWORD name="NORMALIZED" link="ARROW.html#wp756667" />
  <KEYWORD name="HSIZE" link="ARROW.html#wp756670" />
  <KEYWORD name="COLOR" link="ARROW.html#wp756673" />
  <KEYWORD name="HTHICK" link="ARROW.html#wp756676" />
  <KEYWORD name="SOLID" link="ARROW.html#wp756679" />
  <KEYWORD name="THICK" link="ARROW.html#wp756682" />
</ROUTINE>
<ROUTINE name="ASCII_TEMPLATE" link="ASCII_TEMPLATE.html">
  <SYNTAX name="Result = ASCII_TEMPLATE( [Filename] )" type="func" />
  <ARGUMENT name="Filename" link="ASCII_TEMPLATE.html#wp871001" />
  <KEYWORD name="BROWSE_LINES" link="ASCII_TEMPLATE.html#wp871007" />
  <KEYWORD name="CANCEL" link="ASCII_TEMPLATE.html#wp871139" />
  <KEYWORD name="GROUP" link="ASCII_TEMPLATE.html#wp884032" />
</ROUTINE>
<ROUTINE name="ASIN" link="ASIN.html">
  <SYNTAX name="Result = ASIN(X)" type="func" />
  <ARGUMENT name="X" link="ASIN.html#wp675732" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="ASSOC" link="ASSOC.html">
  <SYNTAX name="Result = ASSOC( Unit, Array_Structure [, Offset] )" type="func" />
  <ARGUMENT name="Unit" link="ASSOC.html#wp675744" />
  <ARGUMENT name="Array_Structure" link="ASSOC.html#wp675746" />
  <ARGUMENT name="Offset" link="ASSOC.html#wp675748" />
  <KEYWORD name="PACKED" link="ASSOC.html#wp906241" />
</ROUTINE>
<ROUTINE name="ATAN" link="ATAN.html">
  <SYNTAX name="Result = ATAN(X  )" type="func" />
  <SYNTAX name="Result = ATAN(Y, X)" type="func" />
  <ARGUMENT name="X" link="ATAN.html#wp675765" />
  <ARGUMENT name="Y" link="ATAN.html#wp675767" />
  <KEYWORD name="PHASE" link="ATAN.html#wp995606" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="AXIS" link="AXIS.html">
  <SYNTAX name="AXIS [, X [, Y [, Z]]]" type="pro" />
  <ARGUMENT name="X" link="AXIS.html#wp675781" />
  <ARGUMENT name="Y" link="AXIS.html#wp675781" />
  <ARGUMENT name="Z" link="AXIS.html#wp675781" />
  <KEYWORD name="SAVE" link="AXIS.html#wp986499" />
  <KEYWORD name="XAXIS" link="AXIS.html#wp983775" />
  <KEYWORD name="XLOG" link="AXIS.html#wp983760" />
  <KEYWORD name="YAXIS" link="AXIS.html#wp983765" />
  <KEYWORD name="YLOG" link="AXIS.html#wp983752" />
  <KEYWORD name="YNOZERO" link="AXIS.html#wp158293" />
  <KEYWORD name="ZAXIS" link="AXIS.html#wp983724" />
  <KEYWORD name="CHARSIZE" link="Graphics_Keywords.html#wp266973" />
  <KEYWORD name="CHARTHICK" link="Graphics_Keywords.html#wp331668" />
  <KEYWORD name="COLOR" link="Graphics_Keywords.html#wp315952" />
  <KEYWORD name="DATA" link="Graphics_Keywords.html#wp315961" />
  <KEYWORD name="DEVICE" link="Graphics_Keywords.html#wp315977" />
  <KEYWORD name="FONT" link="Graphics_Keywords.html#wp331795" />
  <KEYWORD name="NODATA" link="Graphics_Keywords.html#wp316018" />
  <KEYWORD name="NOERASE" link="Graphics_Keywords.html#wp316024" />
  <KEYWORD name="NORMAL" link="Graphics_Keywords.html#wp315963" />
  <KEYWORD name="SUBTITLE" link="Graphics_Keywords.html#wp316057" />
  <KEYWORD name="T3D" link="Graphics_Keywords.html#wp315956" />
  <KEYWORD name="TICKLEN" link="Graphics_Keywords.html#wp332207" />
  <KEYWORD name="[XYZ]CHARSIZE" link="Graphics_Keywords.html#wp331699" />
  <KEYWORD name="[XYZ]GRIDSTYLE" link="Graphics_Keywords.html#wp332009" />
  <KEYWORD name="[XYZ]MARGIN" link="Graphics_Keywords.html#wp332038" />
  <KEYWORD name="[XYZ]MINOR" link="Graphics_Keywords.html#wp332061" />
  <KEYWORD name="[XYZ]RANGE" link="Graphics_Keywords.html#wp332090" />
  <KEYWORD name="[XYZ]STYLE" link="Graphics_Keywords.html#wp332116" />
  <KEYWORD name="[XYZ]THICK" link="Graphics_Keywords.html#wp332298" />
  <KEYWORD name="[XYZ]TICKFORMAT" link="Graphics_Keywords.html#wp332347" />
  <KEYWORD name="[XYZ]TICKINTERVAL" link="Graphics_Keywords.html#wp332463" />
  <KEYWORD name="[XYZ]TICKLAYOUT" link="Graphics_Keywords.html#wp332488" />
  <KEYWORD name="[XYZ]TICKLEN" link="Graphics_Keywords.html#wp332513" />
  <KEYWORD name="[XYZ]TICKNAME" link="Graphics_Keywords.html#wp332536" />
  <KEYWORD name="[XYZ]TICKS" link="Graphics_Keywords.html#wp332559" />
  <KEYWORD name="[XYZ]TICKUNITS" link="Graphics_Keywords.html#wp332586" />
  <KEYWORD name="[XYZ]TICKV" link="Graphics_Keywords.html#wp332628" />
  <KEYWORD name="[XYZ]TICK_GET" link="Graphics_Keywords.html#wp332321" />
  <KEYWORD name="[XYZ]TITLE" link="Graphics_Keywords.html#wp316100" />
  <KEYWORD name="ZVALUE" link="Graphics_Keywords.html#wp316102" />
</ROUTINE>
<ROUTINE name="BANDPASS_FILTER" link="BANDPASS_FILTER.html">
  <SYNTAX name="Result = BANDPASS_FILTER( ImageData, LowFreq, HighFreq )" type="func" />
  <ARGUMENT name="ImageData" link="BANDPASS_FILTER.html#wp1044573" />
  <ARGUMENT name="LowFreq" link="BANDPASS_FILTER.html#wp1044575" />
  <ARGUMENT name="HighFreq" link="BANDPASS_FILTER.html#wp1044577" />
  <KEYWORD name="IDEAL" link="BANDPASS_FILTER.html#wp1044581" />
  <KEYWORD name="BUTTERWORTH" link="BANDPASS_FILTER.html#wp1044592" />
  <KEYWORD name="GAUSSIAN" link="BANDPASS_FILTER.html#wp1044603" />
</ROUTINE>
<ROUTINE name="BANDREJECT_FILTER" link="BANDREJECT_FILTER.html">
  <SYNTAX name="Result = BANDREJECT_FILTER( ImageData, LowFreq, HighFreq )" type="func" />
  <ARGUMENT name="ImageData" link="BANDREJECT_FILTER.html#wp1044898" />
  <ARGUMENT name="LowFreq" link="BANDREJECT_FILTER.html#wp1044900" />
  <ARGUMENT name="HighFreq" link="BANDREJECT_FILTER.html#wp1044902" />
  <KEYWORD name="IDEAL" link="BANDREJECT_FILTER.html#wp1044906" />
  <KEYWORD name="BUTTERWORTH" link="BANDREJECT_FILTER.html#wp1044917" />
  <KEYWORD name="GAUSSIAN" link="BANDREJECT_FILTER.html#wp1044929" />
</ROUTINE>
<ROUTINE name="BAR_PLOT" link="BAR_PLOT.html">
  <SYNTAX name="BAR_PLOT, Values" type="pro" />
  <ARGUMENT name="Values" link="BAR_PLOT.html#wp756715" />
  <KEYWORD name="BACKGROUND" link="BAR_PLOT.html#wp756719" />
  <KEYWORD name="BARNAMES" link="BAR_PLOT.html#wp756722" />
  <KEYWORD name="BAROFFSET" link="BAR_PLOT.html#wp756725" />
  <KEYWORD name="BARSPACE" link="BAR_PLOT.html#wp756728" />
  <KEYWORD name="BARWIDTH" link="BAR_PLOT.html#wp756731" />
  <KEYWORD name="BASELINES" link="BAR_PLOT.html#wp756734" />
  <KEYWORD name="BASERANGE" link="BAR_PLOT.html#wp756737" />
  <KEYWORD name="COLORS" link="BAR_PLOT.html#wp756740" />
  <KEYWORD name="OUTLINE" link="BAR_PLOT.html#wp756743" />
  <KEYWORD name="OVERPLOT" link="BAR_PLOT.html#wp756746" />
  <KEYWORD name="ROTATE" link="BAR_PLOT.html#wp756749" />
  <KEYWORD name="TITLE" link="BAR_PLOT.html#wp756752" />
  <KEYWORD name="XTITLE" link="BAR_PLOT.html#wp756755" />
  <KEYWORD name="YTITLE" link="BAR_PLOT.html#wp756758" />
</ROUTINE>
<ROUTINE name="BEGIN...END" link="BEGIN...END.html">
  <SYNTAX name="BEGIN" type="pro" />
  <SYNTAX name="   statements" type="pro" />
  <SYNTAX name="END | ENDIF | ENDELSE | ENDFOR | ENDREP | ENDWHILE" type="pro" />
</ROUTINE>
<ROUTINE name="BESELI" link="BESELI.html">
  <SYNTAX name="Result = BESELI(X, N )" type="func" />
  <ARGUMENT name="X" link="BESELI.html#wp675811" />
  <ARGUMENT name="N" link="BESELI.html#wp989844" />
  <KEYWORD name="DOUBLE" link="BESELI.html#wp998579" />
  <KEYWORD name="ITER" link="BESELI.html#wp998584" />
</ROUTINE>
<ROUTINE name="BESELJ" link="BESELJ.html">
  <SYNTAX name="Result = BESELJ(X, N )" type="func" />
  <ARGUMENT name="X" link="BESELJ.html#wp675820" />
  <ARGUMENT name="N" link="BESELJ.html#wp989899" />
  <KEYWORD name="DOUBLE" link="BESELJ.html#wp998704" />
  <KEYWORD name="ITER" link="BESELJ.html#wp998706" />
</ROUTINE>
<ROUTINE name="BESELK" link="BESELK.html">
  <SYNTAX name="Result = BESELK( X, N )" type="func" />
  <ARGUMENT name="X" link="BESELK.html#wp989449" />
  <ARGUMENT name="N" link="BESELK.html#wp989451" />
  <KEYWORD name="DOUBLE" link="BESELK.html#wp998712" />
  <KEYWORD name="ITER" link="BESELK.html#wp998714" />
</ROUTINE>
<ROUTINE name="BESELY" link="BESELY.html">
  <SYNTAX name="Result = BESELY(X, N )" type="func" />
  <ARGUMENT name="X" link="BESELY.html#wp675829" />
  <ARGUMENT name="N" link="BESELY.html#wp987548" />
  <KEYWORD name="DOUBLE" link="BESELY.html#wp998720" />
  <KEYWORD name="ITER" link="BESELY.html#wp998722" />
</ROUTINE>
<ROUTINE name="BETA" link="BETA.html">
  <SYNTAX name="Result = BETA( Z, W )" type="func" />
  <ARGUMENT name="Z" link="BETA.html#wp50230" />
  <ARGUMENT name="W" link="BETA.html#wp50230" />
  <KEYWORD name="DOUBLE" link="BETA.html#wp50234" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BILINEAR" link="BILINEAR.html">
  <SYNTAX name="Result = BILINEAR(P, IX, JY  )" type="func" />
  <ARGUMENT name="P" link="BILINEAR.html#wp749451" />
  <ARGUMENT name="IX and JY" link="BILINEAR.html#wp749453" />
  <KEYWORD name="MISSING" link="BILINEAR.html#wp996637" />
</ROUTINE>
<ROUTINE name="BIN_DATE" link="BIN_DATE.html">
  <SYNTAX name="Result = BIN_DATE(Ascii_Time)" type="func" />
  <ARGUMENT name="Ascii_Time" link="BIN_DATE.html#wp762131" />
</ROUTINE>
<ROUTINE name="BINARY_TEMPLATE" link="BINARY_TEMPLATE.html">
  <SYNTAX name="Result = BINARY_TEMPLATE ( [Filename]  )" type="func" />
  <ARGUMENT name="Filename" link="BINARY_TEMPLATE.html#wp985254" />
  <KEYWORD name="CANCEL" link="BINARY_TEMPLATE.html#wp985257" />
  <KEYWORD name="GROUP" link="BINARY_TEMPLATE.html#wp985259" />
  <KEYWORD name="N_ROWS" link="BINARY_TEMPLATE.html#wp985261" />
  <KEYWORD name="TEMPLATE" link="BINARY_TEMPLATE.html#wp988405" />
</ROUTINE>
<ROUTINE name="BINDGEN" link="BINDGEN.html">
  <SYNTAX name="Result = BINDGEN(D1 [, ...,D8])" type="func" />
  <ARGUMENT name="Di" link="BINDGEN.html#wp675838" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BINOMIAL" link="BINOMIAL.html">
  <SYNTAX name="Result = BINOMIAL(V, N, P )" type="func" />
  <ARGUMENT name="V" link="BINOMIAL.html#wp53029" />
  <ARGUMENT name="N" link="BINOMIAL.html#wp53031" />
  <ARGUMENT name="P" link="BINOMIAL.html#wp53033" />
  <KEYWORD name="DOUBLE" link="BINOMIAL.html#wp988094" />
  <KEYWORD name="GAUSSIAN" link="BINOMIAL.html#wp988097" />
</ROUTINE>
<ROUTINE name="BIT_FFS" link="BIT_FFS.html">
  <SYNTAX name="Result = BIT_FFS( Value )" type="func" />
  <ARGUMENT name="Value" link="BIT_FFS.html#wp1030348" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BIT_POPULATION" link="BIT_POPULATION.html">
  <SYNTAX name="Result = BIT_POPULATION( Value )" type="func" />
  <ARGUMENT name="Value" link="BIT_POPULATION.html#wp1030515" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BLAS_AXPY" link="BLAS_AXPY.html">
  <SYNTAX name="BLAS_AXPY, Y, A, X [, D1, Loc1 [, D2, Range]]" type="pro" />
  <ARGUMENT name="Y" link="BLAS_AXPY.html#wp907741" />
  <ARGUMENT name="A" link="BLAS_AXPY.html#wp907746" />
  <ARGUMENT name="X" link="BLAS_AXPY.html#wp907753" />
  <ARGUMENT name="D1" link="BLAS_AXPY.html#wp907757" />
  <ARGUMENT name="Loc1" link="BLAS_AXPY.html#wp907761" />
  <ARGUMENT name="D2" link="BLAS_AXPY.html#wp907768" />
  <ARGUMENT name="Range" link="BLAS_AXPY.html#wp907875" />
</ROUTINE>
<ROUTINE name="BLK_CON" link="BLK_CON.html">
  <SYNTAX name="Result = BLK_CON( Filter, Signal )" type="func" />
  <ARGUMENT name="Filter" link="BLK_CON.html#wp749500" />
  <ARGUMENT name="Signal" link="BLK_CON.html#wp37136" />
  <KEYWORD name="B_LENGTH" link="BLK_CON.html#wp749505" />
  <KEYWORD name="DOUBLE" link="BLK_CON.html#wp987871" />
</ROUTINE>
<ROUTINE name="BOX_CURSOR" link="BOX_CURSOR.html">
  <SYNTAX name="BOX_CURSOR, [ X0, Y0, NX, NY" type="pro" />
  <ARGUMENT name="X0" link="BOX_CURSOR.html#wp756807" />
  <ARGUMENT name="Y0" link="BOX_CURSOR.html#wp756807" />
  <ARGUMENT name="NX" link="BOX_CURSOR.html#wp756809" />
  <ARGUMENT name="NY" link="BOX_CURSOR.html#wp756809" />
  <KEYWORD name="INIT" link="BOX_CURSOR.html#wp756813" />
  <KEYWORD name="FIXED_SIZE" link="BOX_CURSOR.html#wp756816" />
  <KEYWORD name="MESSAGE" link="BOX_CURSOR.html#wp756819" />
</ROUTINE>
<ROUTINE name="BREAK" link="BREAK.html">
  <SYNTAX name="BREAK" type="pro" />
</ROUTINE>
<ROUTINE name="BREAKPOINT" link="BREAKPOINT.html">
  <SYNTAX name="BREAKPOINT [, File], Index" type="pro" />
  <ARGUMENT name="File" link="BREAKPOINT.html#wp675857" />
  <ARGUMENT name="Index" link="BREAKPOINT.html#wp675859" />
  <KEYWORD name="AFTER" link="BREAKPOINT.html#wp113854" />
  <KEYWORD name="CLEAR" link="BREAKPOINT.html#wp675862" />
  <KEYWORD name="CONDITION" link="BREAKPOINT.html#wp113859" />
  <KEYWORD name="DISABLE" link="BREAKPOINT.html#wp907385" />
  <KEYWORD name="ENABLE" link="BREAKPOINT.html#wp984755" />
  <KEYWORD name="ON_RECOMPILE" link="BREAKPOINT.html#wp984772" />
  <KEYWORD name="ONCE" link="BREAKPOINT.html#wp990987" />
  <KEYWORD name="SET" link="BREAKPOINT.html#wp675866" />
</ROUTINE>
<ROUTINE name="BROYDEN" link="BROYDEN.html">
  <SYNTAX name="Result = BROYDEN( X, Vecfunc )" type="func" />
  <ARGUMENT name="X" link="BROYDEN.html#wp50264" />
  <ARGUMENT name="Vecfunc" link="BROYDEN.html#wp50266" />
  <KEYWORD name="CHECK" link="BROYDEN.html#wp50283" />
  <KEYWORD name="DOUBLE" link="BROYDEN.html#wp50286" />
  <KEYWORD name="EPS" link="BROYDEN.html#wp50289" />
  <KEYWORD name="ITMAX" link="BROYDEN.html#wp989330" />
  <KEYWORD name="STEPMAX" link="BROYDEN.html#wp50292" />
  <KEYWORD name="TOLF" link="BROYDEN.html#wp50295" />
  <KEYWORD name="TOLMIN" link="BROYDEN.html#wp50298" />
  <KEYWORD name="TOLX" link="BROYDEN.html#wp50301" />
</ROUTINE>
<ROUTINE name="BUTTERWORTH" link="BUTTERWORTH.html">
  <SYNTAX name="Result = BUTTERWORTH( X [, Y [, Z]] )" type="func" />
  <ARGUMENT name="X" link="BUTTERWORTH.html#wp1037565" />
  <ARGUMENT name="Y" link="BUTTERWORTH.html#wp1037625" />
  <ARGUMENT name="Z" link="BUTTERWORTH.html#wp1037630" />
  <KEYWORD name="CUTOFF" link="BUTTERWORTH.html#wp1037570" />
  <KEYWORD name="ORDER" link="BUTTERWORTH.html#wp1037646" />
  <KEYWORD name="ORIGIN" link="BUTTERWORTH.html#wp1037651" />
  <KEYWORD name="XDIM" link="BUTTERWORTH.html#wp1037656" />
  <KEYWORD name="YDIM" link="BUTTERWORTH.html#wp1037662" />
  <KEYWORD name="ZDIM" link="BUTTERWORTH.html#wp1037667" />
</ROUTINE>
<ROUTINE name="BYTARR" link="BYTARR.html">
  <SYNTAX name="Result = BYTARR( D1[, ..., D8] )" type="func" />
  <ARGUMENT name="Di" link="BYTARR.html#wp675875" />
  <KEYWORD name="NOZERO" link="BYTARR.html#wp675878" />
</ROUTINE>
<ROUTINE name="BYTE" link="BYTE.html">
  <SYNTAX name="Result = BYTE( Expression[, Offset [, D1[, ..., D8]]] )" type="func" />
  <ARGUMENT name="Expression" link="BYTE.html#wp675888" />
  <ARGUMENT name="Offset" link="BYTE.html#wp675890" />
  <ARGUMENT name="Di" link="BYTE.html#wp675892" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BYTEORDER" link="BYTEORDER.html">
  <SYNTAX name="BYTEORDER, Variable1, ..., Variablen" type="pro" />
  <ARGUMENT name="Variablen" link="BYTEORDER.html#wp675904" />
  <KEYWORD name="DTOVAX" link="BYTEORDER.html#wp906658" />
  <KEYWORD name="DTOXDR" link="BYTEORDER.html#wp906876" />
  <KEYWORD name="FTOVAX" link="BYTEORDER.html#wp675911" />
  <KEYWORD name="FTOXDR" link="BYTEORDER.html#wp906884" />
  <KEYWORD name="HTONL" link="BYTEORDER.html#wp906665" />
  <KEYWORD name="HTONS" link="BYTEORDER.html#wp675913" />
  <KEYWORD name="L64SWAP" link="BYTEORDER.html#wp965960" />
  <KEYWORD name="LSWAP" link="BYTEORDER.html#wp675915" />
  <KEYWORD name="NTOHL" link="BYTEORDER.html#wp675917" />
  <KEYWORD name="NTOHS" link="BYTEORDER.html#wp675919" />
  <KEYWORD name="SSWAP" link="BYTEORDER.html#wp675921" />
  <KEYWORD name="SWAP_IF_BIG_ENDIAN" link="BYTEORDER.html#wp906711" />
  <KEYWORD name="SWAP_IF_LITTLE_ENDIAN" link="BYTEORDER.html#wp906720" />
  <KEYWORD name="VAXTOD" link="BYTEORDER.html#wp675923" />
  <KEYWORD name="VAXTOF" link="BYTEORDER.html#wp906693" />
  <KEYWORD name="XDRTOD" link="BYTEORDER.html#wp906679" />
  <KEYWORD name="XDRTOF" link="BYTEORDER.html#wp675925" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="BYTSCL" link="BYTSCL.html">
  <SYNTAX name="Result = BYTSCL( Array )" type="func" />
  <ARGUMENT name="Array" link="BYTSCL.html#wp675961" />
  <KEYWORD name="MAX" link="BYTSCL.html#wp675964" />
  <KEYWORD name="MIN" link="BYTSCL.html#wp675966" />
  <KEYWORD name="NAN" link="BYTSCL.html#wp47179" />
  <KEYWORD name="TOP" link="BYTSCL.html#wp675968" />
  <KEYWORD name="TPOOL_MAX_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MAX_ELTS" />
  <KEYWORD name="TPOOL_MIN_ELTS" link="Thread_Pool_Keywords.html#TPOOL_MIN_ELTS" />
  <KEYWORD name="TPOOL_NOTHREAD" link="Thread_Pool_Keywords.html#TPOOL_NOTHREAD" />
</ROUTINE>
<ROUTINE name="C_CORRELATE" link="C_CORRELATE.html">
  <SYNTAX name="Result = C_CORRELATE( X, Y, Lag )" type="func" />
  <ARGUMENT name="X" link="C_CORRELATE.html#wp54449" />
  <ARGUMENT name="Y" link="C_CORRELATE.html#wp54451" />
  <ARGUMENT name="Lag" link="C_CORRELATE.html#wp54453" />
  <KEYWORD name="COVARIANCE" link="C_CORRELATE.html#wp54458" />
  <KEYWORD name="DOUBLE" link="C_CORRELATE.html#wp826756" />
</ROUTINE>
<ROUTINE name="CALDAT" link="CALDAT.html">
  <SYNTAX name="CALDAT, Julian, Month [, Day [, Year [, Hour [, Minute [, Second]]]]]" type="pro" />
  <ARGUMENT name="Julian" link="CALDAT.html#wp762157" />
  <ARGUMENT name="Month" link="CALDAT.html#wp762159" />
  <ARGUMENT name="Day" link="CALDAT.html#wp762161" />
  <ARGUMENT name="Year" link="CALDAT.html#wp762163" />
  <ARGUMENT name="Hour" link="CALDAT.html#wp917871" />
  <ARGUMENT name="Minute" link="CALDAT.html#wp917873" />
  <ARGUMENT name="Second" link="CALDAT.html#wp917875" />
</ROUTINE>
<ROUTINE name="CALENDAR" link="CALENDAR.html">
  <SYNTAX name="CALENDAR [[, Month] , Year]" type="pro" />
  <ARGUMENT name="Month" link="CALENDAR.html#wp762184" />
  <ARGUMENT name="Year" link="CALENDAR.html#wp762186" />
</ROUTINE>
<ROUTINE name="CALL_EXTERNAL" link="CALL_EXTERNAL.html">
  <SYNTAX name="Result = CALL_EXTERNAL(Image, Entry [, P0, ..., PN-1] )" type="func" />
  <ARGUMENT name="Image" link="CALL_EXTERNAL.html#wp905896" />
  <ARGUMENT name="Entry" link="CALL_EXTERNAL.html#wp905902" />
  <ARGUMENT name="P0" link="CALL_EXTERNAL.html#wp905904" />
  <ARGUMENT name="PN-1" link="CALL_EXTERNAL.html#wp905904" />
  <KEYWORD name="ALL_VALUE" link="CALL_EXTERNAL.html#wp905908" />
  <KEYWORD name="B_VALUE" link="CALL_EXTERNAL.html#wp951311" />
  <KEYWORD name="CDECL" link="CALL_EXTERNAL.html#wp905911" />
  <KEYWORD name="D_VALUE" link="CALL_EXTERNAL.html#wp905920" />
  <KEYWORD name="F_VALUE" link="CALL_EXTERNAL.html#wp905923" />
  <KEYWORD name="I_VALUE" link="CALL_EXTERNAL.html#wp905926" />
  <KEYWORD name="L64_VALUE" link="CALL_EXTERNAL.html#wp951332" />
  <KEYWORD name="RETURN_TYPE" link="CALL_EXTERNAL.html#wp1029187" />
  <KEYWORD name="S_VALUE" link="CALL_EXTERNAL.html#wp951354" />